version: '3'
services:
  back-vote:
    image: redis
    container_name: back-vote
    ports:
        - "6379:6379"

  front-vote:
    build: ./azure-vote
    image: front-vote
    container_name: front-vote
    environment:
      REDIS: back-vote
    ports:
        - "83:80"
